using pengdows.crud.enums;
using testbed;
using Xunit;

namespace pengdows.crud.IntegrationTests.Infrastructure;

/// <summary>
/// Locks down basic structural invariants of <see cref="DatabaseTypeCatalog"/> — a reference/
/// discovery catalog, not a live-verification suite (the underlying facts are sourced/verified
/// per each entry's own <see cref="ColumnTypeDescriptor.Notes"/>, not re-checked here).
/// </summary>
public class DatabaseTypeCatalogTests
{
    public static IEnumerable<object[]> PopulatedDatabases()
    {
        yield return new object[] { SupportedDatabase.Db2 };
        yield return new object[] { SupportedDatabase.SingleStore };
        yield return new object[] { SupportedDatabase.SybaseASE };
        yield return new object[] { SupportedDatabase.Spanner };
        yield return new object[] { SupportedDatabase.Informix };
        yield return new object[] { SupportedDatabase.SapHana };
        yield return new object[] { SupportedDatabase.InterBase };
    }

    [Theory]
    [MemberData(nameof(PopulatedDatabases))]
    public void GetColumnTypes_ReturnsNonEmptyCatalog(SupportedDatabase db)
    {
        var types = DatabaseTypeCatalog.GetColumnTypes(db);
        Assert.NotEmpty(types);
    }

    [Theory]
    [MemberData(nameof(PopulatedDatabases))]
    public void GetColumnTypes_EveryEntryHasACanonicalName(SupportedDatabase db)
    {
        foreach (var type in DatabaseTypeCatalog.GetColumnTypes(db))
        {
            Assert.False(string.IsNullOrWhiteSpace(type.CanonicalName));
        }
    }

    [Theory]
    [MemberData(nameof(PopulatedDatabases))]
    public void GetColumnTypes_NoDuplicateCanonicalNames(SupportedDatabase db)
    {
        var names = DatabaseTypeCatalog.GetColumnTypes(db).Select(t => t.CanonicalName).ToList();
        Assert.Equal(names.Count, names.Distinct(StringComparer.Ordinal).Count());
    }

    [Fact]
    public void GetColumnTypes_UnpopulatedDatabase_ReturnsEmptyRatherThanThrowing()
    {
        // e.g. SqlServer is a real, fully supported dialect but deliberately not yet catalogued
        // here (see DatabaseTypeCatalog.cs's file header on sourcing discipline) — querying it
        // should return "nothing catalogued yet", not fail.
        var types = DatabaseTypeCatalog.GetColumnTypes(SupportedDatabase.SqlServer);
        Assert.Empty(types);
    }

    // Sybase ASE's "timestamp" is the case that proves a flat name -> DbType map is insufficient:
    // it looks temporal (the name), but is a row-version value, not a date/time value.
    [Fact]
    public void SybaseTimestamp_IsRowVersionCategory_NotTemporal()
    {
        var timestamp = DatabaseTypeCatalog.GetColumnTypes(SupportedDatabase.SybaseASE)
            .Single(t => t.CanonicalName == "timestamp");

        Assert.Equal(ColumnTypeCategory.RowVersion, timestamp.Category);
        Assert.False(timestamp.IsTemporal);
        Assert.True(timestamp.IsAutoGenerated);
    }

    // Spanner PostgreSQL's "interval" is the opposite case: genuinely temporal, but cannot be
    // stored in a table column at all.
    [Fact]
    public void SpannerInterval_IsTemporal_ButCannotDeclareColumn()
    {
        var interval = DatabaseTypeCatalog.GetColumnTypes(SupportedDatabase.Spanner)
            .Single(t => t.CanonicalName == "interval");

        Assert.True(interval.IsTemporal);
        Assert.False(interval.CanDeclareColumn);
    }

    // InterBase's INT128/DECFLOAT entries exist specifically to warn against copying Firebird 4/5
    // types into the InterBase dialect — both must be marked as rejected, not just omitted.
    [Theory]
    [InlineData("INT128")]
    [InlineData("DECFLOAT")]
    public void InterBase_Firebird4Types_AreMarkedRejected(string canonicalName)
    {
        var entry = DatabaseTypeCatalog.GetColumnTypes(SupportedDatabase.InterBase)
            .Single(t => t.CanonicalName == canonicalName);

        Assert.False(entry.CanDeclareColumn);
        Assert.False(entry.CanReturnFromQuery);
    }
}
