#region

using System.Data;
using pengdows.crud;
using pengdows.crud.attributes;
using pengdows.crud.infrastructure;

#endregion

namespace testbed.DuckDb;

public class DuckDbTestProvider : TestProvider
{
    public DuckDbTestProvider(IDatabaseContext context, IServiceProvider serviceProvider)
        : base(context, serviceProvider)
    {
    }

    protected override Task RunAdditionalTestsAsync() => TestAutoGeneratedIdAsync();

    private async Task TestAutoGeneratedIdAsync()
    {
        Console.WriteLine("Running DuckDB RETURNING clause (auto-generated id)");

        var tableName = _context.WrapObjectName("duckdb_auto_id_table");
        const string seqName = "seq_duckdb_auto_id_test";
        var seqNameQuoted = _context.WrapObjectName(seqName);

        await using var sc = _context.CreateSqlContainer();

        sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
        await sc.ExecuteNonQueryAsync();

        sc.Clear();
        sc.Query.Append($"DROP SEQUENCE IF EXISTS {seqNameQuoted}");
        await sc.ExecuteNonQueryAsync();

        sc.Clear();
        sc.Query.Append($"CREATE SEQUENCE {seqNameQuoted}");
        await sc.ExecuteNonQueryAsync();

        try
        {
            sc.Clear();
            sc.Query.Append($@"
CREATE TABLE {tableName} (
    {_context.WrapObjectName("id")} BIGINT DEFAULT nextval('{seqName}') PRIMARY KEY,
    {_context.WrapObjectName("name")} VARCHAR(100) NOT NULL
)");
            await sc.ExecuteNonQueryAsync();

            var gateway = new TableGateway<DuckDbAutoIdTable, long>(_context);
            var entity = new DuckDbAutoIdTable { Name = "returning-test" };
            var ok = await gateway.CreateAsync(entity);

            if (!ok)
            {
                throw new Exception("DuckDB RETURNING: CreateAsync returned false");
            }

            if (entity.Id == 0)
            {
                throw new Exception(
                    "DuckDB RETURNING clause did not populate Id — INSERT ... RETURNING id returned 0 or null");
            }

            CheckOk($"DuckDB RETURNING: CreateAsync populated Id = {entity.Id} via INSERT ... RETURNING");

            var retrieved = await gateway.RetrieveOneAsync(entity.Id);
            if (retrieved == null || retrieved.Id != entity.Id)
            {
                throw new Exception(
                    $"DuckDB RETURNING: RetrieveOneAsync by returned Id {entity.Id} did not find the row");
            }

            CheckOk($"DuckDB RETURNING: RetrieveOneAsync confirmed row exists with Id = {retrieved.Id}");
        }
        finally
        {
            sc.Clear();
            sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
            await sc.ExecuteNonQueryAsync();

            sc.Clear();
            sc.Query.Append($"DROP SEQUENCE IF EXISTS {seqNameQuoted}");
            await sc.ExecuteNonQueryAsync();
        }
    }

    [Table("duckdb_auto_id_table")]
    private class DuckDbAutoIdTable
    {
        [Id(false)]
        [Column("id", DbType.Int64)]
        public long Id { get; set; }

        [Column("name", DbType.String)]
        public string Name { get; set; } = string.Empty;
    }
}
