// =============================================================================
// FILE: DatabaseTypeCatalog.cs
// PURPOSE: Per-database column-type descriptors for datatype discovery/compatibility testing.
//
// AI SUMMARY:
// - Scope, per the request that produced this file: types that can matter to a DAL as column
//   declarations or returned column metadata. Deliberately excludes: plain ANSI aliases already
//   folded into a canonical entry's Aliases list; internal/query-only expression types with no
//   column-storage meaning; and open-ended user-defined-type escape hatches (Db2 DISTINCT/
//   structured types, Informix DataBlade opaque/distinct types) — those are flagged via
//   IsUserDefined = true on a single catalog-all entry per engine rather than enumerated, because
//   they have no finite list (installed extensions and end users can add more at any time).
// - Deliberately NOT wired into testbed/TestProvider.cs's existing GetIntType/GetLongType/
//   GetBooleanType/GetDateTimeType/GetTextType/GetDecimalType/GetBinaryType/GetGuidType/
//   GetDateTimeOffsetType helpers (see CLAUDE.md item 26 for why those are test-only, and item 19
//   for their production-code-equivalent, IntegrationObjectNameHelper) — this is new, additive
//   reference/discovery infrastructure, not a replacement. Migrating those call sites to consume
//   this catalog is a real, separate follow-up, not attempted here: those helpers are working,
//   tested code with their own live-verified quirks (e.g. InterBaseDialectTests.cs,
//   docs/supported-databases.md), and a blind swap risks silently reintroducing a bug one of those
//   helpers already has a documented fix for.
// - Populated only for the databases with sourced, cited data as of this writing: Db2 LUW 11.5.x,
//   SingleStore, Sybase ASE 16.x, Google Cloud Spanner (PostgreSQL dialect only — pengdows.crud
//   has no GoogleSQL-dialect Spanner support, so that type list is intentionally not modeled
//   here), Informix 14.10, SAP HANA (Cloud QRC 2/2026, with the platform/legacy addendum), and
//   InterBase 15, plus PostgreSQL (shared by Aurora PostgreSQL) and SQL Server 2025, live-verified
//   by TypeRoundTripMatrixTests (TYPE-002). Every other pengdows.crud-supported database (MySQL,
//   MariaDB, Oracle, SQLite, DuckDB, Firebird, CockroachDB, YugabyteDB, TiDB, Snowflake, Aurora
//   MySQL) is deliberately left unpopulated rather than guessed — extend this
//   catalog with the same sourcing discipline (a citable reference or a live-verified fact) when
//   one of those is needed, not by assumption from a "similar" engine.
// - Two real cases prove a flat name -> DbType dictionary is insufficient, which is why this
//   carries structured flags instead: Sybase ASE's predefined `timestamp` UDT LOOKS temporal but
//   is an automatically maintained binary row-version value, not a date/time value at all
//   (IsTemporal = false here, deliberately, despite the name) — and Spanner PostgreSQL's
//   `interval` really is temporal but CanDeclareColumn = false (query-only, cannot be stored in a
//   table column).
// =============================================================================

using pengdows.crud.enums;

namespace testbed;

/// <summary>
/// Broad shape of a column type, for grouping/filtering — not a 1:1 stand-in for <see cref="System.Data.DbType"/>.
/// </summary>
public enum ColumnTypeCategory
{
    Boolean,
    ExactNumeric,
    ApproximateNumeric,
    Character,
    Binary,
    Temporal,
    RowVersion,
    Lob,
    Json,
    Spatial,
    Vector,
    Array,
    UserDefined,
    Other
}

/// <summary>
/// Describes one column-capable (or deliberately NOT column-capable — see <see cref="CanDeclareColumn"/>)
/// type for one database engine. See this file's header for scope and sourcing discipline.
/// </summary>
public sealed record ColumnTypeDescriptor(
    string CanonicalName,
    ColumnTypeCategory Category,
    IReadOnlyList<string>? Aliases = null,
    bool CanDeclareColumn = true,
    bool CanReturnFromQuery = true,
    bool IsUserDefined = false,
    bool IsArray = false,
    bool IsLob = false,
    bool IsBinary = false,
    bool IsTemporal = false,
    bool HasTimeZone = false,
    bool IsUnsigned = false,
    bool IsAutoGenerated = false,
    string? MinVersion = null,
    string? MaxVersion = null,
    string? Notes = null,
    // TYPE-002 live round-trip matrix (pengdows.crud.IntegrationTests TypeRoundTripMatrixTests):
    // an entry with a ClrType is written through the gateway as Sample, read back through the
    // gateway and DataReaderMapper, and (when Comparable) filtered with WHERE v = @p.
    string? Declaration = null,
    Type? ClrType = null,
    System.Data.DbType? DbType = null,
    object? Sample = null,
    bool Comparable = true);

public static class DatabaseTypeCatalog
{
    public static IReadOnlyList<ColumnTypeDescriptor> GetColumnTypes(SupportedDatabase product) => product switch
    {
        SupportedDatabase.Db2 => Db2Types,
        SupportedDatabase.SingleStore => SingleStoreTypes,
        SupportedDatabase.SybaseASE => SybaseTypes,
        // pengdows.crud's Spanner support targets the PostgreSQL dialect exclusively (confirmed
        // via SpannerDialect : PostgreSqlDialect and every live-verification note in CLAUDE.md's
        // "Adding a New Database" items 14-30) — the GoogleSQL dialect type list from the source
        // audit is not modeled here since there is no corresponding dialect to describe.
        SupportedDatabase.Spanner => SpannerPostgreSqlTypes,
        SupportedDatabase.Informix => InformixTypes,
        SupportedDatabase.SapHana => HanaTypes,
        SupportedDatabase.InterBase => InterBaseTypes,
        SupportedDatabase.PostgreSql or SupportedDatabase.AuroraPostgreSql => PostgreSqlTypes,
        SupportedDatabase.SqlServer => SqlServerTypes,
        _ => Array.Empty<ColumnTypeDescriptor>()
    };

    // ── PostgreSQL 16 ───────────────────────────────────────────────────────
    // Source: PostgreSQL 16 documentation, chapter 8 "Data Types" (core types only; extension
    // types such as hstore/PostGIS/pgvector are covered by their own tests). Entries with a
    // ClrType are live-verified by TypeRoundTripMatrixTests; geometric, bit-string, text-search
    // and pg_lsn types have no pengdows CLR mapping and carry no ClrType.
    private static readonly IReadOnlyList<ColumnTypeDescriptor> PostgreSqlTypes = new ColumnTypeDescriptor[]
    {
        new("SMALLINT", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INT2" },
            Declaration: "SMALLINT", ClrType: typeof(short), DbType: System.Data.DbType.Int16, Sample: short.MinValue),
        new("INTEGER", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INT", "INT4" },
            Declaration: "INTEGER", ClrType: typeof(int), DbType: System.Data.DbType.Int32, Sample: int.MinValue),
        new("BIGINT", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INT8" },
            Declaration: "BIGINT", ClrType: typeof(long), DbType: System.Data.DbType.Int64, Sample: long.MaxValue),
        new("NUMERIC(p,s)", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "DECIMAL(p,s)" },
            Declaration: "NUMERIC(38,10)", ClrType: typeof(decimal), DbType: System.Data.DbType.Decimal, Sample: 1234567890123456.0123456789m),
        new("REAL", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "FLOAT4" },
            Declaration: "REAL", ClrType: typeof(float), DbType: System.Data.DbType.Single, Sample: 1.5f),
        new("DOUBLE PRECISION", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "FLOAT8" },
            Declaration: "DOUBLE PRECISION", ClrType: typeof(double), DbType: System.Data.DbType.Double, Sample: -1.25e300),
        new("MONEY", ColumnTypeCategory.ExactNumeric,
            Declaration: "MONEY", ClrType: typeof(decimal), DbType: System.Data.DbType.Currency, Sample: 12345.67m),
        new("BOOLEAN", ColumnTypeCategory.Boolean, Aliases: new[] { "BOOL" },
            Declaration: "BOOLEAN", ClrType: typeof(bool), DbType: System.Data.DbType.Boolean, Sample: true),
        new("CHAR(n)", ColumnTypeCategory.Character, Aliases: new[] { "CHARACTER(n)" },
            Declaration: "CHAR(10)", ClrType: typeof(string), DbType: System.Data.DbType.StringFixedLength, Sample: "abcdefghij"),
        new("VARCHAR(n)", ColumnTypeCategory.Character, Aliases: new[] { "CHARACTER VARYING(n)" },
            Declaration: "VARCHAR(50)", ClrType: typeof(string), DbType: System.Data.DbType.String, Sample: "héllo wörld ✓"),
        new("TEXT", ColumnTypeCategory.Character,
            Declaration: "TEXT", ClrType: typeof(string), DbType: System.Data.DbType.String, Sample: new string('x', 5000)),
        new("BYTEA", ColumnTypeCategory.Binary, IsBinary: true,
            Declaration: "BYTEA", ClrType: typeof(byte[]), DbType: System.Data.DbType.Binary, Sample: new byte[] { 0, 1, 2, 0xFE, 0xFF }),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true,
            Declaration: "DATE", ClrType: typeof(DateOnly), DbType: System.Data.DbType.Date, Sample: new DateOnly(2026, 10, 1)),
        new("TIME", ColumnTypeCategory.Temporal, IsTemporal: true, Aliases: new[] { "TIME WITHOUT TIME ZONE" },
            Declaration: "TIME(6)", ClrType: typeof(TimeOnly), DbType: System.Data.DbType.Time, Sample: new TimeOnly(13, 45, 30, 123, 456)),
        new("TIMESTAMP", ColumnTypeCategory.Temporal, IsTemporal: true, Aliases: new[] { "TIMESTAMP WITHOUT TIME ZONE" },
            Declaration: "TIMESTAMP(6)", ClrType: typeof(DateTime), DbType: System.Data.DbType.DateTime2,
            Sample: new DateTime(2026, 10, 1, 13, 45, 30, 123, 456, DateTimeKind.Utc)),
        new("TIMESTAMPTZ", ColumnTypeCategory.Temporal, IsTemporal: true, HasTimeZone: true, Aliases: new[] { "TIMESTAMP WITH TIME ZONE" },
            Declaration: "TIMESTAMPTZ(6)", ClrType: typeof(DateTimeOffset), DbType: System.Data.DbType.DateTimeOffset,
            Sample: new DateTimeOffset(2026, 10, 1, 13, 45, 30, 123, 456, TimeSpan.FromHours(-5))),
        new("INTERVAL", ColumnTypeCategory.Temporal, IsTemporal: true,
            Declaration: "INTERVAL", ClrType: typeof(TimeSpan), DbType: System.Data.DbType.Object, Sample: new TimeSpan(3, 4, 5, 6, 789)),
        new("UUID", ColumnTypeCategory.Other,
            Declaration: "UUID", ClrType: typeof(Guid), DbType: System.Data.DbType.Guid, Sample: new Guid("0190f3a1-7b2c-7d3e-8f40-123456789abc")),
        new("JSON", ColumnTypeCategory.Json,
            Declaration: "JSON", ClrType: typeof(pengdows.crud.types.valueobjects.JsonValue), DbType: System.Data.DbType.Object,
            Sample: new pengdows.crud.types.valueobjects.JsonValue("{\"a\":1}"), Comparable: false,
            Notes: "No equality operator for json."),
        new("JSONB", ColumnTypeCategory.Json,
            Declaration: "JSONB", ClrType: typeof(pengdows.crud.types.valueobjects.JsonValue), DbType: System.Data.DbType.Object,
            Sample: new pengdows.crud.types.valueobjects.JsonValue("{\"a\":1}"), Comparable: false),
        new("XML", ColumnTypeCategory.Other,
            Declaration: "XML", ClrType: typeof(string), DbType: System.Data.DbType.Xml, Sample: "<a b=\"1\">x</a>", Comparable: false,
            Notes: "No equality operator for xml."),
        new("INET", ColumnTypeCategory.Other,
            Declaration: "INET", ClrType: typeof(pengdows.crud.types.valueobjects.Inet), DbType: System.Data.DbType.Object,
            Sample: pengdows.crud.types.valueobjects.Inet.Parse("192.168.1.10/24")),
        new("CIDR", ColumnTypeCategory.Other,
            Declaration: "CIDR", ClrType: typeof(pengdows.crud.types.valueobjects.Cidr), DbType: System.Data.DbType.Object,
            Sample: pengdows.crud.types.valueobjects.Cidr.Parse("10.0.0.0/8")),
        new("MACADDR", ColumnTypeCategory.Other,
            Declaration: "MACADDR", ClrType: typeof(pengdows.crud.types.valueobjects.MacAddress), DbType: System.Data.DbType.Object,
            Sample: pengdows.crud.types.valueobjects.MacAddress.Parse("08:00:2b:01:02:03")),
        new("INT4RANGE", ColumnTypeCategory.Other,
            Declaration: "INT4RANGE", ClrType: typeof(pengdows.crud.types.valueobjects.Range<int>), DbType: System.Data.DbType.Object,
            Sample: new pengdows.crud.types.valueobjects.Range<int>(1, 10, true, false)),
        new("INTEGER[]", ColumnTypeCategory.Array, IsArray: true,
            Declaration: "INTEGER[]", ClrType: typeof(int[]), DbType: System.Data.DbType.Object, Sample: new[] { 1, -2, 3 }),
        new("TEXT[]", ColumnTypeCategory.Array, IsArray: true,
            Declaration: "TEXT[]", ClrType: typeof(string[]), DbType: System.Data.DbType.Object, Sample: new[] { "a", "b c" }),
        new("POINT", ColumnTypeCategory.Spatial, Notes: "Geometric types (point, line, lseg, box, path, polygon, circle) have no pengdows CLR type."),
        new("BIT(n)", ColumnTypeCategory.Other, Aliases: new[] { "BIT VARYING(n)" }, Notes: "No pengdows CLR mapping."),
        new("TSVECTOR", ColumnTypeCategory.Other, Aliases: new[] { "TSQUERY" }, Notes: "Text-search types; no pengdows CLR mapping."),
    };

    // ── SQL Server 2025 ─────────────────────────────────────────────────────
    // Source: Microsoft Learn, "Data types (Transact-SQL)". Samples respect each type's
    // precision (datetime 1/300 s, smalldatetime 1 min). rowversion is server-generated and
    // sql_variant has no single CLR type, so neither carries a ClrType. Live-verified by
    // TypeRoundTripMatrixTests against SQL Server 2025 (json/vector need 2025).
    private static readonly IReadOnlyList<ColumnTypeDescriptor> SqlServerTypes = new ColumnTypeDescriptor[]
    {
        new("BIT", ColumnTypeCategory.Boolean,
            Declaration: "BIT", ClrType: typeof(bool), DbType: System.Data.DbType.Boolean, Sample: true),
        new("TINYINT", ColumnTypeCategory.ExactNumeric, IsUnsigned: true,
            Declaration: "TINYINT", ClrType: typeof(byte), DbType: System.Data.DbType.Byte, Sample: (byte)255),
        new("SMALLINT", ColumnTypeCategory.ExactNumeric,
            Declaration: "SMALLINT", ClrType: typeof(short), DbType: System.Data.DbType.Int16, Sample: short.MinValue),
        new("INT", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INTEGER" },
            Declaration: "INT", ClrType: typeof(int), DbType: System.Data.DbType.Int32, Sample: int.MinValue),
        new("BIGINT", ColumnTypeCategory.ExactNumeric,
            Declaration: "BIGINT", ClrType: typeof(long), DbType: System.Data.DbType.Int64, Sample: long.MaxValue),
        new("DECIMAL(p,s)", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "NUMERIC(p,s)" },
            Declaration: "DECIMAL(38,10)", ClrType: typeof(decimal), DbType: System.Data.DbType.Decimal, Sample: 1234567890123456.0123456789m),
        new("MONEY", ColumnTypeCategory.ExactNumeric,
            Declaration: "MONEY", ClrType: typeof(decimal), DbType: System.Data.DbType.Currency, Sample: 922337203685477.5807m),
        new("SMALLMONEY", ColumnTypeCategory.ExactNumeric,
            Declaration: "SMALLMONEY", ClrType: typeof(decimal), DbType: System.Data.DbType.Currency, Sample: -214748.3648m),
        new("REAL", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "FLOAT(24)" },
            Declaration: "REAL", ClrType: typeof(float), DbType: System.Data.DbType.Single, Sample: 1.5f),
        new("FLOAT", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "FLOAT(53)", "DOUBLE PRECISION" },
            Declaration: "FLOAT", ClrType: typeof(double), DbType: System.Data.DbType.Double, Sample: -1.25e300),
        new("CHAR(n)", ColumnTypeCategory.Character,
            Declaration: "CHAR(10)", ClrType: typeof(string), DbType: System.Data.DbType.AnsiStringFixedLength, Sample: "abcdefghij"),
        new("VARCHAR(n)", ColumnTypeCategory.Character,
            Declaration: "VARCHAR(50)", ClrType: typeof(string), DbType: System.Data.DbType.AnsiString, Sample: "plain ascii text"),
        new("VARCHAR(MAX)", ColumnTypeCategory.Lob, IsLob: true,
            Declaration: "VARCHAR(MAX)", ClrType: typeof(string), DbType: System.Data.DbType.AnsiString, Sample: new string('x', 9000)),
        new("NCHAR(n)", ColumnTypeCategory.Character,
            Declaration: "NCHAR(10)", ClrType: typeof(string), DbType: System.Data.DbType.StringFixedLength, Sample: "ábcdéfghíj"),
        new("NVARCHAR(n)", ColumnTypeCategory.Character,
            Declaration: "NVARCHAR(50)", ClrType: typeof(string), DbType: System.Data.DbType.String, Sample: "héllo wörld ✓"),
        new("NVARCHAR(MAX)", ColumnTypeCategory.Lob, IsLob: true,
            Declaration: "NVARCHAR(MAX)", ClrType: typeof(string), DbType: System.Data.DbType.String, Sample: new string('é', 9000)),
        new("TEXT", ColumnTypeCategory.Lob, IsLob: true, Aliases: new[] { "NTEXT", "IMAGE" },
            Declaration: "TEXT", ClrType: typeof(string), DbType: System.Data.DbType.AnsiString, Sample: "legacy text", Comparable: false,
            Notes: "Deprecated LOB types; no = operator."),
        new("BINARY(n)", ColumnTypeCategory.Binary, IsBinary: true,
            Declaration: "BINARY(5)", ClrType: typeof(byte[]), DbType: System.Data.DbType.Binary, Sample: new byte[] { 0, 1, 2, 0xFE, 0xFF }),
        new("VARBINARY(n)", ColumnTypeCategory.Binary, IsBinary: true,
            Declaration: "VARBINARY(50)", ClrType: typeof(byte[]), DbType: System.Data.DbType.Binary, Sample: new byte[] { 9, 8, 7 }),
        new("VARBINARY(MAX)", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true,
            Declaration: "VARBINARY(MAX)", ClrType: typeof(byte[]), DbType: System.Data.DbType.Binary, Sample: Enumerable.Range(0, 9000).Select(i => (byte)i).ToArray()),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true,
            Declaration: "DATE", ClrType: typeof(DateOnly), DbType: System.Data.DbType.Date, Sample: new DateOnly(2026, 10, 1)),
        new("TIME(n)", ColumnTypeCategory.Temporal, IsTemporal: true,
            Declaration: "TIME(7)", ClrType: typeof(TimeOnly), DbType: System.Data.DbType.Time, Sample: new TimeOnly(13, 45, 30, 123, 456)),
        new("DATETIME", ColumnTypeCategory.Temporal, IsTemporal: true,
            Declaration: "DATETIME", ClrType: typeof(DateTime), DbType: System.Data.DbType.DateTime,
            Sample: new DateTime(2026, 10, 1, 13, 45, 30, DateTimeKind.Utc)),
        new("SMALLDATETIME", ColumnTypeCategory.Temporal, IsTemporal: true,
            Declaration: "SMALLDATETIME", ClrType: typeof(DateTime), DbType: System.Data.DbType.DateTime,
            Sample: new DateTime(2026, 10, 1, 13, 45, 0, DateTimeKind.Utc)),
        new("DATETIME2(n)", ColumnTypeCategory.Temporal, IsTemporal: true,
            Declaration: "DATETIME2(7)", ClrType: typeof(DateTime), DbType: System.Data.DbType.DateTime2,
            Sample: new DateTime(2026, 10, 1, 13, 45, 30, 123, 456, DateTimeKind.Utc).AddTicks(7)),
        new("DATETIMEOFFSET(n)", ColumnTypeCategory.Temporal, IsTemporal: true, HasTimeZone: true,
            Declaration: "DATETIMEOFFSET(7)", ClrType: typeof(DateTimeOffset), DbType: System.Data.DbType.DateTimeOffset,
            Sample: new DateTimeOffset(2026, 10, 1, 13, 45, 30, 123, 456, TimeSpan.FromHours(-5))),
        new("UNIQUEIDENTIFIER", ColumnTypeCategory.Other,
            Declaration: "UNIQUEIDENTIFIER", ClrType: typeof(Guid), DbType: System.Data.DbType.Guid, Sample: new Guid("0190f3a1-7b2c-7d3e-8f40-123456789abc")),
        new("XML", ColumnTypeCategory.Other,
            Declaration: "XML", ClrType: typeof(string), DbType: System.Data.DbType.Xml, Sample: "<a b=\"1\">x</a>", Comparable: false,
            Notes: "No = operator for xml."),
        new("JSON", ColumnTypeCategory.Json, MinVersion: "2025",
            Declaration: "JSON", ClrType: typeof(pengdows.crud.types.valueobjects.JsonValue), DbType: System.Data.DbType.Object,
            Sample: new pengdows.crud.types.valueobjects.JsonValue("{\"a\":1}"), Comparable: false),
        new("HIERARCHYID", ColumnTypeCategory.Other,
            Declaration: "HIERARCHYID", ClrType: typeof(pengdows.crud.types.valueobjects.HierarchyId), DbType: System.Data.DbType.Object,
            Sample: pengdows.crud.types.valueobjects.HierarchyId.Parse("/1/3/")),
        new("GEOMETRY", ColumnTypeCategory.Spatial,
            Declaration: "GEOMETRY", ClrType: typeof(pengdows.crud.types.valueobjects.Geometry), DbType: System.Data.DbType.Object,
            Sample: pengdows.crud.types.valueobjects.Geometry.FromWellKnownText("POINT (1 2)", 0), Comparable: false),
        new("GEOGRAPHY", ColumnTypeCategory.Spatial,
            Declaration: "GEOGRAPHY", ClrType: typeof(pengdows.crud.types.valueobjects.Geography), DbType: System.Data.DbType.Object,
            Sample: pengdows.crud.types.valueobjects.Geography.FromWellKnownText("POINT (-87.6298 41.8781)", 4326), Comparable: false),
        new("VECTOR(n)", ColumnTypeCategory.Vector, MinVersion: "2025",
            Declaration: "VECTOR(3)", ClrType: typeof(float[]), DbType: System.Data.DbType.Object, Sample: new[] { 1f, 2f, 3.5f }, Comparable: false),
        new("ROWVERSION", ColumnTypeCategory.RowVersion, IsAutoGenerated: true, Aliases: new[] { "TIMESTAMP" },
            Notes: "Server-generated; covered by the [Version] tests."),
        new("SQL_VARIANT", ColumnTypeCategory.Other, Notes: "No single CLR type."),
    };

    // ── Db2 LUW 11.5.x ──────────────────────────────────────────────────────
    // Source: IBM Db2 11.5 SQL reference (data types / CREATE TABLE). Special cases NOT modeled
    // as ordinary scalar entries: SYSPROC.DB2SECURITYLABEL-style security-label columns, and
    // "TIMESTAMP WITH TIME ZONE" — that SQL type is Db2 for z/OS only, not Db2 LUW, and must not
    // be added here just because IBM's common client drivers expose the CLI/JDBC constant for it.
    private static readonly IReadOnlyList<ColumnTypeDescriptor> Db2Types = new ColumnTypeDescriptor[]
    {
        new("SMALLINT", ColumnTypeCategory.ExactNumeric),
        new("INTEGER", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INT" }),
        new("BIGINT", ColumnTypeCategory.ExactNumeric),
        new("DECIMAL", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "NUMERIC" }),
        new("DECFLOAT(16)", ColumnTypeCategory.ExactNumeric),
        new("DECFLOAT(34)", ColumnTypeCategory.ExactNumeric),
        new("REAL", ColumnTypeCategory.ApproximateNumeric),
        new("DOUBLE", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "DOUBLE PRECISION" }),
        new("FLOAT(n)", ColumnTypeCategory.ApproximateNumeric),
        new("CHAR(n)", ColumnTypeCategory.Character, Aliases: new[] { "CHARACTER(n)" }),
        new("VARCHAR(n)", ColumnTypeCategory.Character, Aliases: new[] { "CHARACTER VARYING(n)", "CHAR VARYING(n)" }),
        new("CLOB(n)", ColumnTypeCategory.Lob, IsLob: true),
        new("LONG VARCHAR", ColumnTypeCategory.Character, Notes: "Supported but deprecated by IBM."),
        new("GRAPHIC(n)", ColumnTypeCategory.Character, Notes: "Double-byte character (national-character alias NCHAR in Unicode databases)."),
        new("VARGRAPHIC(n)", ColumnTypeCategory.Character, Notes: "National-character alias NVARCHAR in Unicode databases."),
        new("DBCLOB(n)", ColumnTypeCategory.Lob, IsLob: true, Notes: "National-character alias NCLOB in Unicode databases."),
        new("LONG VARGRAPHIC", ColumnTypeCategory.Character, Notes: "Supported but deprecated by IBM."),
        new("BINARY(n)", ColumnTypeCategory.Binary, IsBinary: true, Aliases: new[] { "CHAR(n) FOR BIT DATA" }),
        new("VARBINARY(n)", ColumnTypeCategory.Binary, IsBinary: true, Aliases: new[] { "BINARY VARYING(n)", "VARCHAR(n) FOR BIT DATA" }),
        new("BLOB(n)", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true, Aliases: new[] { "BINARY LARGE OBJECT(n)" }),
        new("LONG VARCHAR FOR BIT DATA", ColumnTypeCategory.Binary, IsBinary: true, Notes: "Supported but deprecated by IBM."),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIMESTAMP(p)", ColumnTypeCategory.Temporal, IsTemporal: true,
            Notes: "\"TIMESTAMP WITH TIME ZONE\" is Db2 for z/OS only — do NOT add it here for Db2 LUW."),
        new("BOOLEAN", ColumnTypeCategory.Boolean),
        new("XML", ColumnTypeCategory.Other),
        new("<DISTINCT/structured type or REF(structured-type)>", ColumnTypeCategory.UserDefined, IsUserDefined: true,
            Notes: "Db2 also permits ARRAY/CURSOR/ROW user-defined types, but those aren't ordinary scalar table-column types.")
    };

    // ── SingleStore (Helios) ────────────────────────────────────────────────
    // Source: SingleStore self-managed/Helios docs (integer/real/temporal/binary-string/other type
    // reference pages). pengdows.crud detects SingleStore at runtime and delegates to MySqlDialect
    // (see CLAUDE.md's supported-databases.md SingleStore note) — this list documents SingleStore's
    // OWN broader type surface for reference, not what pengdows.crud's MySQL-delegating dialect
    // actively exercises today.
    private static readonly IReadOnlyList<ColumnTypeDescriptor> SingleStoreTypes = new ColumnTypeDescriptor[]
    {
        new("BOOL", ColumnTypeCategory.Boolean, Aliases: new[] { "BOOLEAN" }),
        new("BIT", ColumnTypeCategory.ExactNumeric),
        new("TINYINT", ColumnTypeCategory.ExactNumeric, Notes: "Accepts UNSIGNED."),
        new("SMALLINT", ColumnTypeCategory.ExactNumeric, Notes: "Accepts UNSIGNED."),
        new("MEDIUMINT", ColumnTypeCategory.ExactNumeric, Notes: "Accepts UNSIGNED."),
        new("INT", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INTEGER" }, Notes: "Accepts UNSIGNED."),
        new("BIGINT", ColumnTypeCategory.ExactNumeric, Notes: "Accepts UNSIGNED."),
        new("FLOAT", ColumnTypeCategory.ApproximateNumeric),
        new("DOUBLE", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "REAL" }),
        new("DECIMAL(p,s)", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "DEC(p,s)", "FIXED(p,s)", "NUMERIC(p,s)" }),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIME", ColumnTypeCategory.Temporal, IsTemporal: true, Aliases: new[] { "TIME(6)" }),
        new("DATETIME", ColumnTypeCategory.Temporal, IsTemporal: true, Aliases: new[] { "DATETIME(6)" }),
        new("TIMESTAMP", ColumnTypeCategory.Temporal, IsTemporal: true, Aliases: new[] { "TIMESTAMP(6)" }),
        new("YEAR", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("CHAR(n)", ColumnTypeCategory.Character),
        new("VARCHAR(n)", ColumnTypeCategory.Character),
        new("BINARY(n)", ColumnTypeCategory.Binary, IsBinary: true),
        new("VARBINARY(n)", ColumnTypeCategory.Binary, IsBinary: true),
        new("TINYTEXT", ColumnTypeCategory.Lob, IsLob: true),
        new("TEXT", ColumnTypeCategory.Lob, IsLob: true),
        new("MEDIUMTEXT", ColumnTypeCategory.Lob, IsLob: true),
        new("LONGTEXT", ColumnTypeCategory.Lob, IsLob: true),
        new("TINYBLOB", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("BLOB", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("MEDIUMBLOB", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("LONGBLOB", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("ENUM(...)", ColumnTypeCategory.Other),
        new("SET(...)", ColumnTypeCategory.Other),
        new("JSON", ColumnTypeCategory.Json),
        new("BSON", ColumnTypeCategory.Other,
            Notes: "Tied to SingleStore Kai-created tables specifically — detect it, but don't advertise generic BSON DDL support the way JSON is."),
        new("GEOGRAPHY", ColumnTypeCategory.Spatial),
        new("GEOGRAPHYPOINT", ColumnTypeCategory.Spatial),
        new("VECTOR(n)", ColumnTypeCategory.Vector, Aliases: new[] { "VECTOR(n,I8)", "VECTOR(n,I16)", "VECTOR(n,I32)", "VECTOR(n,I64)", "VECTOR(n,F32)", "VECTOR(n,F64)" })
    };

    // ── Sybase ASE / SAP ASE 16.x ───────────────────────────────────────────
    // Source: SAP ASE 16.0 SP04 reference manual + SAP Help Portal (system/user-defined datatypes).
    private static readonly IReadOnlyList<ColumnTypeDescriptor> SybaseTypes = new ColumnTypeDescriptor[]
    {
        new("BIGINT", ColumnTypeCategory.ExactNumeric),
        new("INT", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INTEGER" }),
        new("SMALLINT", ColumnTypeCategory.ExactNumeric),
        new("TINYINT", ColumnTypeCategory.ExactNumeric),
        new("UNSIGNED BIGINT", ColumnTypeCategory.ExactNumeric, IsUnsigned: true),
        new("UNSIGNED INT", ColumnTypeCategory.ExactNumeric, IsUnsigned: true),
        new("UNSIGNED SMALLINT", ColumnTypeCategory.ExactNumeric, IsUnsigned: true),
        new("NUMERIC(p,s)", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "DECIMAL(p,s)", "DEC(p,s)" }),
        new("FLOAT", ColumnTypeCategory.ApproximateNumeric),
        new("DOUBLE PRECISION", ColumnTypeCategory.ApproximateNumeric),
        new("REAL", ColumnTypeCategory.ApproximateNumeric),
        new("MONEY", ColumnTypeCategory.ExactNumeric),
        new("SMALLMONEY", ColumnTypeCategory.ExactNumeric),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("DATETIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("SMALLDATETIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("BIGDATETIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("BIGTIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("CHAR", ColumnTypeCategory.Character),
        new("VARCHAR", ColumnTypeCategory.Character),
        new("NCHAR", ColumnTypeCategory.Character),
        new("NVARCHAR", ColumnTypeCategory.Character),
        new("UNICHAR", ColumnTypeCategory.Character),
        new("UNIVARCHAR", ColumnTypeCategory.Character),
        new("TEXT", ColumnTypeCategory.Lob, IsLob: true),
        new("UNITEXT", ColumnTypeCategory.Lob, IsLob: true),
        new("BINARY", ColumnTypeCategory.Binary, IsBinary: true),
        new("VARBINARY", ColumnTypeCategory.Binary, IsBinary: true),
        new("IMAGE", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("BIT", ColumnTypeCategory.Boolean),
        new("XML", ColumnTypeCategory.Other),
        // Predefined UDTs shipped by ASE itself (not ordinary vendor scalar types).
        new("timestamp", ColumnTypeCategory.RowVersion, IsUserDefined: true, IsAutoGenerated: true, IsTemporal: false,
            Notes: "DANGEROUS for generic mapping: an automatically maintained BINARY row-version value, NOT a date/time value, despite the name."),
        new("sysname", ColumnTypeCategory.Character, IsUserDefined: true),
        new("longsysname", ColumnTypeCategory.Character, IsUserDefined: true),
        new("<intn/uintn/datetimn/moneyn nullable-wrapper types>", ColumnTypeCategory.Other, IsUserDefined: true, CanDeclareColumn: false,
            Notes: "ASE's internal nullable-storage types — never expose these as user-declarable column types.")
    };

    // ── Google Cloud Spanner — PostgreSQL dialect ───────────────────────────
    // Source: Google Cloud Spanner PostgreSQL data-types reference. See CLAUDE.md's "Adding a New
    // Database" items 17/27/28 for several live-verified quirks layered on top of this DDL-level
    // list (Npgsql binding gaps, precision-modifier rejection on numeric, missing plain timestamp).
    private static readonly IReadOnlyList<ColumnTypeDescriptor> SpannerPostgreSqlTypes = new ColumnTypeDescriptor[]
    {
        new("bool", ColumnTypeCategory.Boolean, Aliases: new[] { "boolean" }),
        new("bytea", ColumnTypeCategory.Binary, IsBinary: true),
        new("date", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("float4", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "real" }),
        new("float8", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "double precision" }),
        new("int", ColumnTypeCategory.ExactNumeric,
            Notes: "NASTY quirk, confirmed live (CLAUDE.md item 27): plain \"int\" is 64-bit here, effectively mapping to int8, NOT PostgreSQL's normal 32-bit int4."),
        new("int8", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "bigint" }),
        new("numeric", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "decimal" },
            Notes: "Fixed-precision — CONFIRMED live a precision/scale modifier is rejected outright (CLAUDE.md item 27); must be declared bare."),
        new("jsonb", ColumnTypeCategory.Json),
        new("timestamptz", ColumnTypeCategory.Temporal, IsTemporal: true, HasTimeZone: true, Aliases: new[] { "timestamp with time zone" },
            Notes: "\"timestamp without time zone\" does NOT exist here — CONFIRMED live (CLAUDE.md item 17)."),
        new("varchar", ColumnTypeCategory.Character, Aliases: new[] { "character varying" }),
        new("text", ColumnTypeCategory.Character),
        new("uuid", ColumnTypeCategory.Other,
            Notes: "Real DDL type, but CONFIRMED live that Npgsql cannot bind NpgsqlDbType.Uuid against it (CLAUDE.md item 27) — pengdows.crud's SpannerDialect works around this with GuidFormat.String + varchar(36), not this native type."),
        new("<T>[]", ColumnTypeCategory.Array, IsArray: true, Notes: "Arrays of any supported non-array element type."),
        new("smallserial/serial/bigserial/serial2/serial4/serial8", ColumnTypeCategory.ExactNumeric, IsAutoGenerated: true,
            Notes: "Accepted spellings, but implemented as bigint identity columns, not independent storage types."),
        new("interval", ColumnTypeCategory.Temporal, IsTemporal: true, CanDeclareColumn: false,
            Notes: "Query-only — CANNOT be stored in a table column, despite genuinely being a temporal type."),
        new("timestamp", ColumnTypeCategory.Temporal, CanDeclareColumn: false, CanReturnFromQuery: false,
            Notes: "\"timestamp without time zone\" is NOT supported at all."),
        new("char", ColumnTypeCategory.Character, CanDeclareColumn: false, CanReturnFromQuery: false,
            Notes: "PostgreSQL's single-character \"char\" type is NOT supported.")
    };

    // ── Informix 14.10 ──────────────────────────────────────────────────────
    // Source: IBM Informix 14.10 data type reference (scalar + complex types). Informix's
    // extensible-type system (DISTINCT/OPAQUE, plus module-specific predefined opaque types for
    // spatial/time-series/large-object-locator DataBlades) means there is NO finite type list for
    // this engine — unknown Informix types should be treated as UDTs by pengdows.crud tooling, not
    // treated as evidence the core dialect has a closed enumeration.
    private static readonly IReadOnlyList<ColumnTypeDescriptor> InformixTypes = new ColumnTypeDescriptor[]
    {
        new("BIGINT", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INT8" }),
        new("BIGSERIAL", ColumnTypeCategory.ExactNumeric, IsAutoGenerated: true, Aliases: new[] { "SERIAL8" }),
        new("INTEGER", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "INT" }),
        new("SERIAL", ColumnTypeCategory.ExactNumeric, IsAutoGenerated: true),
        new("SMALLINT", ColumnTypeCategory.ExactNumeric),
        new("DECIMAL", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "DEC", "NUMERIC" }),
        new("MONEY", ColumnTypeCategory.ExactNumeric),
        new("FLOAT", ColumnTypeCategory.ApproximateNumeric),
        new("DOUBLE PRECISION", ColumnTypeCategory.ApproximateNumeric),
        new("SMALLFLOAT", ColumnTypeCategory.ApproximateNumeric, Aliases: new[] { "REAL" }),
        new("CHAR", ColumnTypeCategory.Character, Aliases: new[] { "CHARACTER" }),
        new("VARCHAR", ColumnTypeCategory.Character, Aliases: new[] { "CHARACTER VARYING" }),
        new("NCHAR", ColumnTypeCategory.Character),
        new("NVARCHAR", ColumnTypeCategory.Character),
        new("LVARCHAR", ColumnTypeCategory.Character,
            Notes: "Confirmed live (CLAUDE.md/testbed): plain VARCHAR is capped at 255 bytes; use LVARCHAR (up to 32739 bytes) for longer text."),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("DATETIME", ColumnTypeCategory.Temporal, IsTemporal: true, Notes: "Requires an explicit precision qualifier, e.g. DATETIME YEAR TO FRACTION(5)."),
        new("INTERVAL", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("BOOLEAN", ColumnTypeCategory.Boolean,
            Notes: "Real declarable type, but CONFIRMED live that binding it as a parameter breaks comparison against Informix's positional-parameter Int16 boolean representation — testbed uses SMALLINT instead (see TestProvider.GetBooleanType)."),
        new("BYTE", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("TEXT", ColumnTypeCategory.Lob, IsLob: true),
        new("BLOB", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("CLOB", ColumnTypeCategory.Lob, IsLob: true),
        new("JSON", ColumnTypeCategory.Json),
        new("BSON", ColumnTypeCategory.Other),
        new("LIST(element_type NOT NULL)", ColumnTypeCategory.Array, IsArray: true),
        new("SET(element_type NOT NULL)", ColumnTypeCategory.Array, IsArray: true),
        new("MULTISET(element_type NOT NULL)", ColumnTypeCategory.Array, IsArray: true),
        new("ROW(...)", ColumnTypeCategory.UserDefined, Notes: "Named or unnamed ROW types."),
        new("<DISTINCT/OPAQUE type>", ColumnTypeCategory.UserDefined, IsUserDefined: true,
            Notes: "Includes DataBlade-provided predefined opaque types (spatial, time-series, large-object locators, etc.) — no finite list exists; treat any unrecognized Informix type name as a UDT, not an error.")
    };

    // ── SAP HANA ─────────────────────────────────────────────────────────────
    // Source: SAP HANA Cloud SQL reference (QRC 2/2026) for the Cloud column, cross-checked live
    // against a real saplabs/hanaexpress 2.00.088.00 (on-prem/Express) container for this project's
    // actual dialect target. IMPORTANT DISCREPANCY, confirmed live and worth preserving: this
    // project's HanaDialect/testbed rely on a bare "DATETIME" column type working, and it DOES —
    // confirmed live ("Create table: OK" against a real hanaexpress container, testbed logs from
    // this session) — even though HANA Cloud's own QRC 2/2026 core-types documentation does not
    // list DATETIME at all (only DATE/TIME/SECONDDATE/TIMESTAMP). Trust the live result for the
    // on-prem/Express edition this dialect targets over the newer Cloud product line's documented
    // list; do not "fix" TestProvider.GetDateTimeType's HANA behavior based on this catalog alone.
    private static readonly IReadOnlyList<ColumnTypeDescriptor> HanaTypes = new ColumnTypeDescriptor[]
    {
        new("TINYINT", ColumnTypeCategory.ExactNumeric),
        new("SMALLINT", ColumnTypeCategory.ExactNumeric),
        new("INTEGER", ColumnTypeCategory.ExactNumeric),
        new("BIGINT", ColumnTypeCategory.ExactNumeric),
        new("SMALLDECIMAL", ColumnTypeCategory.ExactNumeric),
        new("DECIMAL", ColumnTypeCategory.ExactNumeric),
        new("REAL", ColumnTypeCategory.ApproximateNumeric),
        new("DOUBLE", ColumnTypeCategory.ApproximateNumeric),
        new("BOOLEAN", ColumnTypeCategory.Boolean),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("SECONDDATE", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIMESTAMP", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("VARCHAR", ColumnTypeCategory.Character,
            Notes: "HANA Cloud: effectively an alias for Unicode NVARCHAR."),
        new("NVARCHAR", ColumnTypeCategory.Character),
        new("VARBINARY", ColumnTypeCategory.Binary, IsBinary: true),
        new("BINARY(n)", ColumnTypeCategory.Binary, IsBinary: true,
            Notes: "HANA Cloud's top-level QRC 2/2026 summary table lists only VARBINARY, but the current binary-type doc page also documents fixed-length BINARY(n) — support/detect both rather than trusting the summary table alone."),
        new("BLOB", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true),
        new("CLOB", ColumnTypeCategory.Lob, IsLob: true),
        new("NCLOB", ColumnTypeCategory.Lob, IsLob: true, Notes: "HANA Cloud: CLOB effectively aliases NCLOB."),
        new("ARRAY", ColumnTypeCategory.Array, IsArray: true),
        new("ST_GEOMETRY", ColumnTypeCategory.Spatial),
        new("ST_POINT", ColumnTypeCategory.Spatial),
        new("REAL_VECTOR(n)", ColumnTypeCategory.Vector, MinVersion: "HANA Cloud / newer HANA 2.0 revisions"),
        new("HALF_VECTOR(n)", ColumnTypeCategory.Vector, MinVersion: "HANA Cloud / newer HANA 2.0 revisions"),
        // HANA 2.0 platform legacy/compatibility additions, version/revision-dependent.
        new("CHAR", ColumnTypeCategory.Character, MaxVersion: "legacy compatibility only",
            Notes: "CHAR and NCHAR remain available only for legacy compatibility; NOT available at all on HANA Cloud for new usage patterns typically recommended."),
        new("ALPHANUM", ColumnTypeCategory.Character, MaxVersion: "HANA 2.0 platform", Notes: "NOT available in HANA Cloud."),
        new("SHORTTEXT", ColumnTypeCategory.Character, MaxVersion: "HANA 2.0 platform",
            Notes: "A specialized HANA column definition, not an ordinary ANSI string type — don't normalize it as plain VARCHAR."),
        new("TEXT", ColumnTypeCategory.Lob, IsLob: true, MaxVersion: "HANA 2.0 platform", Notes: "Specialized full-text-indexed column definition, not an ordinary CLOB."),
        new("BINTEXT", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true, MaxVersion: "HANA 2.0 platform")
    };

    // ── InterBase 15 ─────────────────────────────────────────────────────────
    // Source: Embarcadero InterBase 15 DocWiki (data types / fixed-decimal data types), fully
    // cross-verified live against a real InterBase 15.1.0.42 server for this session's
    // InterBaseDialect work (see InterBaseDialect.cs's file-level summary and CLAUDE.md item 32).
    private static readonly IReadOnlyList<ColumnTypeDescriptor> InterBaseTypes = new ColumnTypeDescriptor[]
    {
        new("SMALLINT", ColumnTypeCategory.ExactNumeric),
        new("INTEGER", ColumnTypeCategory.ExactNumeric, Notes: "Confirmed live: bare \"INT\" also works as an alias."),
        new("DECIMAL(p,s)", ColumnTypeCategory.ExactNumeric, Aliases: new[] { "NUMERIC(p,s)" },
            Notes: "The real 64-bit-range idiom — CONFIRMED live that NEITHER BIGINT NOR INT64 exists as a declarable type at all (SQLCODE -607, same domain-lookup-failure signature both share). INT64 exists only as an internal storage representation for high-precision NUMERIC/DECIMAL."),
        new("FLOAT", ColumnTypeCategory.ApproximateNumeric),
        new("DOUBLE PRECISION", ColumnTypeCategory.ApproximateNumeric),
        new("CHAR(n)", ColumnTypeCategory.Character, Aliases: new[] { "CHARACTER(n)" }),
        new("VARCHAR(n)", ColumnTypeCategory.Character, Aliases: new[] { "CHAR VARYING(n)", "CHARACTER VARYING(n)" }),
        new("NCHAR(n)", ColumnTypeCategory.Character, Aliases: new[] { "NATIONAL CHAR(n)", "NATIONAL CHARACTER(n)" }, Notes: "Plus their VARYING forms."),
        new("DATE", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIME", ColumnTypeCategory.Temporal, IsTemporal: true),
        new("TIMESTAMP", ColumnTypeCategory.Temporal, IsTemporal: true,
            Notes: "CONFIRMED live: no time-zone-aware temporal type exists at all — \"TIMESTAMP WITH TIME ZONE\"/\"TIME WITH TIME ZONE\" both fail as genuine syntax errors (SQLCODE -104). Binding a raw DbType.DateTimeOffset parameter fails at the driver level; InterBaseDialect.CreateDbParameter coerces to UTC DateTime instead."),
        new("BOOLEAN", ColumnTypeCategory.Boolean, Notes: "Confirmed live to exist as a native type (unlike Firebird pre-3.0's SMALLINT-only era)."),
        new("BLOB", ColumnTypeCategory.Lob, IsBinary: true, IsLob: true,
            Notes: "CONFIRMED live: cannot be used in a WHERE \"=\" comparison at all (\"BLOB and array data types are not supported for compare operation\") — a genuine InterBase restriction NOT shared by Firebird despite both calling the type BLOB."),
        new("<array of scalar type>", ColumnTypeCategory.Array, IsArray: true,
            Notes: "InterBase allows arrays of essentially any supported scalar type except BLOB, including multidimensional arrays — not exercised by pengdows.crud's InterBaseDialect."),
        new("INT128", ColumnTypeCategory.ExactNumeric, CanDeclareColumn: false, CanReturnFromQuery: false,
            Notes: "Do NOT copy this Firebird 4/5 type into InterBase — CONFIRMED REJECTED live with the same SQLCODE -607 domain-lookup-failure signature as BIGINT."),
        new("DECFLOAT", ColumnTypeCategory.ExactNumeric, CanDeclareColumn: false, CanReturnFromQuery: false,
            Notes: "Do NOT copy this Firebird 4/5 type into InterBase — CONFIRMED REJECTED live with the same SQLCODE -607 signature.")
    };
}
