// =============================================================================
// FILE: HanaDialect.cs
// PURPOSE: SAP HANA (column-store, in-memory RDBMS) dialect implementation.
//
// AI SUMMARY:
// - LIVE-VERIFIED end-to-end against a real saplabs/hanaexpress 2.00.088.00.1760424921
//   container (HXE) run by hand via Docker (no reproducible testbed container in this pass —
//   see the opt-in note below), using both the bundled hdbsql client and the real
//   Sap.Data.Hana.Net.v8.0 2.29.27 ADO.NET driver: identifier case folding, LIMIT/OFFSET paging,
//   MERGE INTO, IDENTITY + CURRENT_IDENTITY_VALUE(), stored procedure CALL syntax, savepoints,
//   isolation level acceptance, and live constraint-violation exception shapes all confirmed.
// - Driver: Sap.Data.Hana.Net.v8.0 (SAP-published, public NuGet.org, SAP Developer License
//   Agreement 3.2 — same "freely downloadable, vendor-licensed" shape as Oracle ODP.NET/IBM
//   Db2). Factory: Sap.Data.Hana.HanaFactory.Instance. GetSchema("DataSourceInformation")
//   reports DataSourceProductName = "HANA", ParameterMarkerFormat = "?".
// - Docker/CI: NOT wired into the always-on testbed matrix. saplabs/hanaexpress documents
//   16-32GB RAM for a working container — far beyond a standard CI runner and beyond every
//   other testbed container — so this is opt-in for resource reasons (INCLUDE_SAPHANA=true),
//   a different category from Snowflake's opt-in (which has no Docker image at all).
// - Parameters: positional "?" only, no named-parameter support — matches Informix's shape.
//   Confirmed live via a real positional INSERT with ordered HanaParameter objects.
// - Identifier quoting: ANSI double quotes. CONFIRMED live: an unquoted identifier
//   ("CREATE COLUMN TABLE CaseTest") folds to uppercase (stored as CASETEST); a quoted one
//   ("CREATE COLUMN TABLE \"CaseTest3\"") preserves exact case. Same fold-to-uppercase-when-
//   unquoted behavior as Oracle, verified independently rather than assumed from it.
// - Pagination: LIMIT n OFFSET m, CONFIRMED live. The SQL:2008 "OFFSET n ROWS FETCH NEXT m ROWS
//   ONLY" form is CONFIRMED REJECTED ("257: sql syntax error ... incorrect syntax near \"1\"") —
//   do not assume Db2/SQL-Server-style paging.
// - MERGE: MERGE INTO ... WHEN MATCHED/WHEN NOT MATCHED is supported, CONFIRMED live for both
//   branches, but the base RenderMergeSource's "USING (VALUES (...)) AS s (...)" row-constructor
//   shape is CONFIRMED REJECTED ("257: sql syntax error ... incorrect syntax near \"VALUES\"").
//   Overridden here with an Oracle/DUAL-shaped "USING (SELECT ... FROM DUMMY) s" source, which
//   IS accepted. HANA also has a native "UPSERT t (cols) VALUES (...) WITH PRIMARY KEY"
//   statement, deliberately not used here — MERGE reuses the framework's existing SupportsMerge
//   path with zero new cross-cutting upsert-style code, at no proven cost.
// - Batch insert: CONFIRMED live that the ANSI multi-row VALUES clause
//   ("INSERT INTO t VALUES (1,'a'), (2,'b')") is rejected — same limitation as
//   SQLite/MySQL/MariaDB/Firebird/Informix. Falls back to one INSERT per entity.
// - Generated keys: IDENTITY column (GENERATED BY DEFAULT AS IDENTITY; column-store tables
//   only, not supported on row-store) plus "SELECT CURRENT_IDENTITY_VALUE() FROM DUMMY"
//   immediately after INSERT on the same connection. CONFIRMED live across multiple sequential
//   inserts on one connection. SAP's own documentation flags CURRENT_IDENTITY_VALUE() as
//   unreliable across *concurrent* sessions sharing identity columns — not a concern for
//   pengdows.crud's own usage, which issues the follow-up SELECT on the same connection within
//   the same operation, never across a pooled hand-off.
// - Procedures: CALL proc(args) via SQLSCRIPT, CONFIRMED live including an OUT parameter bound
//   through a "?" placeholder.
// - Savepoints: SAVEPOINT / ROLLBACK TO SAVEPOINT / RELEASE SAVEPOINT all CONFIRMED live inside
//   a real transaction (unlike Oracle, which has no RELEASE SAVEPOINT at all).
// - DROP TABLE IF EXISTS: CONFIRMED REJECTED, same limitation as Oracle.
// - Isolation levels: HanaConnection.BeginTransaction accepted ReadUncommitted, ReadCommitted,
//   RepeatableRead, and Serializable without error (Snapshot was correctly rejected by the
//   driver itself) — CONFIRMED live. Whether ReadUncommitted delivers genuine dirty reads on the
//   server, versus a silent upgrade to ReadCommitted, was NOT verified (would require a second
//   concurrent session) — unlike TiDB's documented parses-but-silently-downgrades SERIALIZABLE
//   case, nothing here contradicts the level being genuinely honored.
// - Exception classification: CONFIRMED live via a real HanaException that
//   HanaException.ErrorCode is *always* the generic COM HRESULT -2147467259 regardless of
//   violation kind, and HanaException.SqlState is an *empty string* for every violation kind
//   except unique (which the driver leaves at "23000") — neither is usable for classification
//   via the .NET driver. The only reliable discriminator is HanaException.NativeError, which the
//   framework's shared TryGetProviderErrorCode already finds via reflection (it probes
//   "Number" -> "SqliteErrorCode" -> "NativeError" in that order), so no extra dialect-specific
//   reflection is needed here. Real codes captured live: 301 (unique), 461 (FK on insert/update,
//   parent missing), 462 (FK on delete/update, dependent child still exists), 287 (NOT NULL),
//   677 (CHECK). Deadlock (133) and lock-wait-timeout (131) are sourced from SAP's own HANA Lock
//   Analysis FAQ (KBA 1999998), not live-reproduced this session (requires two contending
//   sessions).
// - GUIDs: HanaDbType (the driver's provider-specific type enum) has no native UUID-style
//   member — confirmed by enumerating the real enum. Stored as a client-generated hyphenated
//   string, matching every other dialect without a native GUID column type.
// =============================================================================

using System.Data;
using System.Data.Common;
using Microsoft.Extensions.Logging;
using pengdows.crud.@internal;
using pengdows.crud.enums;
using pengdows.crud.infrastructure;

namespace pengdows.crud.dialects;

/// <summary>
/// SAP HANA dialect.
/// </summary>
/// <remarks>
/// <para>
/// <strong>UPSERT:</strong> Uses MERGE INTO with a "USING (SELECT ... FROM DUMMY) s" source
/// (HANA rejects the VALUES-row-constructor source shape outright).
/// </para>
/// <para>
/// <strong>Parameters:</strong> Positional "?" only, no named-parameter support.
/// </para>
/// </remarks>
internal sealed class HanaDialect : SqlDialect
{
    internal HanaDialect(DbProviderFactory factory, ILogger logger)
        : base(factory, logger)
    {
    }

    public override SupportedDatabase DatabaseType => SupportedDatabase.SapHana;

    // Positional-only parameter markers; confirmed live via DataSourceInformation
    // (ParameterMarkerFormat == "?") and a real positional INSERT.
    public override string ParameterMarker => "?";
    public override bool SupportsNamedParameters => false;

    // Confirmed via DataSourceInformation.ParameterNameMaxLength.
    public override int ParameterNameMaxLength => 128;

    // Schema-qualified object names are real and documented (SYSTEM.TABLE, etc.); unquoted
    // schema/table names fold to uppercase, quoted ones are case-sensitive (confirmed live —
    // see file-level AI SUMMARY).
    public override bool SupportsNamespaces => true;

    // CONFIRMED live: HANA rejects the SQL:2008 "OFFSET n ROWS FETCH NEXT m ROWS ONLY" form
    // outright, but accepts MySQL/PostgreSQL-style "LIMIT m OFFSET n".
    public override bool SupportsOffsetFetch => false;
    public override bool SupportsLimitOffset => true;

    // CONFIRMED live: MERGE INTO ... WHEN MATCHED/WHEN NOT MATCHED works for both branches, but
    // only with a SELECT-based (not VALUES-based) USING source — see RenderMergeSource below.
    public override bool SupportsMerge => true;

    // CONFIRMED live: the ANSI multi-row VALUES clause is rejected ("257: sql syntax error ...
    // incorrect syntax near \",\""). Falls back to one BuildCreate per entity, the same safe
    // path SQLite/MySQL/MariaDB/Firebird/Informix use for the same reason.
    public override bool SupportsBatchInsert => false;

    // CONFIRMED live: CALL proc(?, ?) with an OUT parameter executes correctly.
    public override ProcWrappingStyle ProcWrappingStyle => ProcWrappingStyle.Call;

    // CONFIRMED live: GENERATED BY DEFAULT AS IDENTITY on a column-store table.
    public override bool SupportsIdentityColumns => true;

    // CONFIRMED live: "DROP TABLE IF EXISTS" is rejected outright, same limitation as Oracle.
    public override bool SupportsDropTableIfExists => false;

    // CONFIRMED live: SAVEPOINT / ROLLBACK TO SAVEPOINT / RELEASE SAVEPOINT all succeed inside a
    // real transaction — full capability set, unlike Oracle (no RELEASE SAVEPOINT at all).
    public override bool SupportsSavepoints => true;

    // GUIDs stored as CHAR(36)/VARCHAR(36) strings (client-generated) — HanaDbType has no
    // native UUID-shaped member.
    protected override GuidStorageFormat GuidFormat => GuidStorageFormat.String;

    /// <summary>
    /// HANA rejects the base "USING (VALUES (...)) AS s (col1, col2, ...)" row-constructor MERGE
    /// source outright (CONFIRMED live), but accepts an Oracle/DUAL-shaped
    /// "USING (SELECT ... FROM DUMMY) s" derived table.
    /// </summary>
    public override string RenderMergeSource(IReadOnlyList<IColumnInfo> columns,
        IReadOnlyList<string> parameterNames)
    {
        if (columns == null)
        {
            throw new ArgumentNullException(nameof(columns));
        }

        if (parameterNames == null)
        {
            throw new ArgumentNullException(nameof(parameterNames));
        }

        if (columns.Count != parameterNames.Count)
        {
            throw new ArgumentException("Column and parameter counts must match.");
        }

        var select = SbLite.Create(stackalloc char[SbLite.DefaultStack]);
        for (var i = 0; i < columns.Count; i++)
        {
            if (i > 0)
            {
                select.Append(", ");
            }

            var placeholder = MakeParameterName(parameterNames[i]);
            if (columns[i].IsJsonType)
            {
                placeholder = RenderJsonArgument(placeholder, columns[i]);
            }

            select.Append(placeholder);
            select.Append(" AS ");
            select.Append(WrapObjectName(columns[i].Name));
        }

        return string.Concat("USING (SELECT ", select.ToString(), " FROM DUMMY) s");
    }

    public override void AppendPaging(ISqlQueryBuilder query, int offset, int limit)
    {
        if (offset < 0)
        {
            throw new ArgumentOutOfRangeException(nameof(offset), offset, "Must be >= 0.");
        }

        if (limit <= 0)
        {
            throw new ArgumentOutOfRangeException(nameof(limit), limit, "Must be > 0.");
        }

        // CONFIRMED live: LIMIT/OFFSET only — see SupportsOffsetFetch above.
        query.Append(" LIMIT ").Append(limit);
        if (offset > 0)
        {
            query.Append(" OFFSET ").Append(offset);
        }
    }

    // Deliberately NOT wired up as GeneratedKeyPlan.SessionScopedFunction, even though
    // "SELECT CURRENT_IDENTITY_VALUE() FROM DUMMY" immediately after INSERT was CONFIRMED live
    // to work correctly across multiple sequential inserts on one manually-held connection (see
    // file-level AI SUMMARY). GeneratedKeyPlanReachabilityTests.cs locks down a real, previously
    // fixed hazard (CORE-016/TEST-010): TableGateway.Core.cs's default path treats
    // SessionScopedFunction as a PRIMARY, non-fallback mechanism, and a session-scoped
    // last-insert-id query is not guaranteed to land on the same *pooled* physical connection
    // that ran the INSERT — the exact two-lease hazard CompoundStatement/ReaderInsertedId/
    // Returning exist to avoid. CompoundStatement (INSERT + follow-up query as one command text)
    // was also CONFIRMED REJECTED live ("257: sql syntax error ... incorrect syntax near
    // \"SELECT\"" — HANA does not support multiple semicolon-separated statements in a single
    // command). With SupportsInsertReturning left at its default false and
    // HasSessionScopedLastIdFunction left at its default false, the base GetGeneratedKeyPlan()
    // already resolves to the safe universal fallback, GeneratedKeyPlan.CorrelationToken — no
    // override needed here.

    public override string GetVersionQuery()
    {
        return "SELECT VERSION FROM SYS.M_DATABASE";
    }

    // CONFIRMED live via HanaConnection.BeginTransaction(IsolationLevel) — see file-level AI
    // SUMMARY for the ReadUncommitted caveat.
    internal override HashSet<IsolationLevel> GetSupportedIsolationLevels(bool allowSnapshotIsolation) => new()
    {
        IsolationLevel.ReadUncommitted,
        IsolationLevel.ReadCommitted,
        IsolationLevel.RepeatableRead,
        IsolationLevel.Serializable
    };

    internal override Dictionary<IsolationProfile, IsolationLevel> GetIsolationProfileMapping(bool allowSnapshotIsolation) => new()
    {
        [IsolationProfile.SafeNonBlockingReads] = IsolationLevel.ReadCommitted,
        [IsolationProfile.StrictConsistency] = IsolationLevel.Serializable,
        [IsolationProfile.FastWithRisks] = IsolationLevel.ReadUncommitted
    };

    // All four codes below were captured live from a real Sap.Data.Hana.HanaException thrown
    // against a real saplabs/hanaexpress container (see file-level AI SUMMARY). TryGetProviderErrorCode
    // already finds HanaException.NativeError via reflection — SqlState/ErrorCode are both
    // unusable for classification via this driver.
    public override bool IsUniqueViolation(DbException ex) =>
        TryGetProviderErrorCode(ex) == 301;

    // 461: insert/update references a parent row that does not exist.
    // 462: delete/update blocked because a dependent child row still exists.
    public override bool IsForeignKeyViolation(DbException ex) =>
        TryGetProviderErrorCode(ex) is 461 or 462;

    public override bool IsNotNullViolation(DbException ex) =>
        TryGetProviderErrorCode(ex) == 287;

    public override bool IsCheckConstraintViolation(DbException ex) =>
        TryGetProviderErrorCode(ex) == 677;

    // ConstraintViolation is deliberately not re-checked here — SqlDialect.ClassifyException
    // already checks IsUniqueViolation/IsForeignKeyViolation/IsNotNullViolation/
    // IsCheckConstraintViolation before ever calling this method (see Oracle's identical
    // rationale comment).
    protected override bool TryClassifyProviderException(DbException ex, out DbErrorCategory category)
    {
        var code = TryGetProviderErrorCode(ex);

        // 133: "transaction rolled back by detected deadlock" (SAP KBA 1999998 / 2658020).
        // NOT live-reproduced this session — requires two contending sessions.
        if (code == 133)
        {
            category = DbErrorCategory.Deadlock;
            return true;
        }

        // 131: "transaction rolled back by lock wait timeout" (SAP KBA 1999998 / 2658020).
        // NOT live-reproduced this session.
        if (code == 131)
        {
            category = DbErrorCategory.Timeout;
            return true;
        }

        category = DbErrorCategory.Unknown;
        return false;
    }
}
