#region

using pengdows.crud;

#endregion

namespace testbed.Firebird;

public class FirebirdTestProvider : TestProvider
{
    private readonly IDatabaseContext context;

    public FirebirdTestProvider(IDatabaseContext context, IServiceProvider serviceProvider)
        : base(context, serviceProvider)
    {
        this.context = context;
    }

    public override async Task CreateTable()
    {
        var sqlContainer = context.CreateSqlContainer();
        var qp = context.QuotePrefix;
        var qs = context.QuoteSuffix;

        // Drop table if exists (Firebird 4.0+)
        sqlContainer.Query.AppendFormat(
            "DROP TABLE IF EXISTS {0}test_table{1}", qp, qs);

        try
        {
            await sqlContainer.ExecuteNonQueryAsync();
        }
        catch (Exception ex)
        {
            Console.WriteLine($"Drop failed: {ex.Message}");
        }

        sqlContainer.Clear();
        sqlContainer.Query.AppendFormat(@"
CREATE TABLE {0}test_table{1} (
    {0}id{1} BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    {0}name{1} VARCHAR(100) NOT NULL,
    {0}description{1} VARCHAR(1000) NOT NULL,
    {0}value{1} INTEGER NOT NULL,
    {0}is_active{1} BOOLEAN NOT NULL,
    {0}created_at{1} TIMESTAMP NOT NULL,
    {0}created_by{1} VARCHAR(100) NOT NULL,
    {0}updated_at{1} TIMESTAMP NOT NULL,
    {0}updated_by{1} VARCHAR(100) NOT NULL
)", qp, qs);

        await sqlContainer.ExecuteNonQueryAsync();
        Console.WriteLine("Table created successfully");
    }
}