using pengdows.crud;
using testbed.PostgreSQL;

namespace testbed.Spanner;

/// <summary>
/// Spanner rides <see cref="PostgreSQLTestProvider"/>'s PostgreSQL-wire-compatible test suite, but
/// its PostgreSQL interface (via PGAdapter) has a materially narrower type system than real
/// PostgreSQL — see SpannerDialect.cs's file-level summary for the verified-live gaps. <see cref="PostgreSQLTestProvider.CreateTable"/>'s own <c>test_table</c> DDL
/// hardcodes plain <c>TIMESTAMP</c> (no time zone) for <c>created_at</c>/<c>updated_at</c>, which
/// Spanner's PostgreSQL interface rejects outright (<c>P0001: Type &lt;timestamp&gt; is not
/// supported.</c>) — and because that DDL failure was caught, logged, and silently ignored
/// ("Continuing anyways"), <c>test_table</c> never actually got created, and every later operation
/// against it failed with <c>relation "test_table" does not exist</c> instead of surfacing the real
/// root cause. This override fixes the column type only — everything else PostgreSQLTestProvider
/// does is otherwise reused as-is.
/// </summary>
public class SpannerTestProvider : PostgreSQLTestProvider
{
    public SpannerTestProvider(IDatabaseContext context, IServiceProvider serviceProvider)
        : base(context, serviceProvider)
    {
    }

    public override async Task CreateTable()
    {
        var databaseContext = _context;
        var sqlContainer = databaseContext.CreateSqlContainer();
        var tableName = databaseContext.WrapObjectName("test_table");
        var idColumn = databaseContext.WrapObjectName("id");
        var nameColumn = databaseContext.WrapObjectName("name");
        var descriptionColumn = databaseContext.WrapObjectName("description");
        var valueColumn = databaseContext.WrapObjectName("value");
        var isActiveColumn = databaseContext.WrapObjectName("is_active");
        var createdAtColumn = databaseContext.WrapObjectName("created_at");
        var createdByColumn = databaseContext.WrapObjectName("created_by");
        var updatedAtColumn = databaseContext.WrapObjectName("updated_at");
        var updatedByColumn = databaseContext.WrapObjectName("updated_by");
        sqlContainer.Query.AppendFormat("DROP TABLE IF EXISTS {0}", tableName);
        try
        {
            await sqlContainer.ExecuteNonQueryAsync();
        }
        catch
        {
            // Table did not exist, ignore
        }

        sqlContainer.Clear();
        sqlContainer.Query.AppendFormat(@"
-- Create table
CREATE TABLE {0} (
    {1} BIGINT PRIMARY KEY,
    {2} VARCHAR(100) NOT NULL,
    {3} VARCHAR(1000) NOT NULL,
    {4} INT NOT NULL,
    {5} BOOLEAN NOT NULL,
    {6} TIMESTAMP WITH TIME ZONE NOT NULL,
    {7} VARCHAR(100) NOT NULL,
    {8} TIMESTAMP WITH TIME ZONE NOT NULL,
    {9} VARCHAR(100) NOT NULL
);
", tableName, idColumn, nameColumn, descriptionColumn, valueColumn, isActiveColumn, createdAtColumn,
            createdByColumn, updatedAtColumn, updatedByColumn);
        // Unlike PostgreSQLTestProvider.CreateTable, do NOT swallow a failure here: a silently
        // ignored CREATE TABLE failure is exactly what turned this DDL bug into a much harder to
        // diagnose "relation test_table does not exist" crash three tests later.
        await sqlContainer.ExecuteNonQueryAsync();
    }

    /// <summary>
    /// Verified live: Spanner rejects <c>GENERATED ALWAYS AS IDENTITY</c> ("P0001: Only
    /// &lt;GENERATED BY DEFAULT&gt; is supported for identity column."), so PostgreSQLTestProvider's
    /// OVERRIDING SYSTEM VALUE path cannot exist here. What a caller actually relies on - upserting a
    /// row with a client-supplied id into an identity column, then updating it by upsert - is tested
    /// against Spanner's only identity form, <c>GENERATED BY DEFAULT</c>.
    /// </summary>
    protected override async Task RunAdditionalTestsAsync()
    {
        var tableName = _context.WrapObjectName("spanner_explicit_identity_upsert");
        await using var container = _context.CreateSqlContainer();

        container.Query.Append($"DROP TABLE IF EXISTS {tableName}");
        await container.ExecuteNonQueryAsync();

        try
        {
            container.Clear();
            container.Query.Append($"CREATE TABLE {tableName} (");
            container.Query.Append($"{_context.WrapObjectName("id")} BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, ");
            container.Query.Append($"{_context.WrapObjectName("value")} VARCHAR(100) NOT NULL)");
            await container.ExecuteNonQueryAsync();

            var gateway = new TableGateway<SpannerExplicitIdentityUpsertRow, long>(_context);
            var row = new SpannerExplicitIdentityUpsertRow { Id = 42, Value = "before" };
            await gateway.UpsertAsync(row);
            row.Value = "after";
            await gateway.UpsertAsync(row);

            var loaded = await gateway.RetrieveOneAsync(42);
            if (loaded?.Value != "after")
            {
                throw new Exception(
                    $"Spanner explicit identity upsert did not persist the updated value (got '{loaded?.Value}')");
            }

            CheckOk("  [Spanner] Explicit-id upsert into a GENERATED BY DEFAULT identity column: OK");
        }
        finally
        {
            container.Clear();
            container.Query.Append($"DROP TABLE IF EXISTS {tableName}");
            await container.ExecuteNonQueryAsync();
        }
    }

    [pengdows.crud.attributes.Table("spanner_explicit_identity_upsert")]
    private class SpannerExplicitIdentityUpsertRow
    {
        [pengdows.crud.attributes.Id]
        [pengdows.crud.attributes.Column("id", System.Data.DbType.Int64)]
        public long Id { get; set; }

        [pengdows.crud.attributes.Column("value", System.Data.DbType.String)]
        public string Value { get; set; } = string.Empty;
    }
}
