#region

using pengdows.crud;
using pengdows.crud.attributes;
using pengdows.crud.exceptions;

#endregion

namespace testbed.Db2;

public class Db2TestProvider : TestProvider
{
    public Db2TestProvider(IDatabaseContext context, IServiceProvider serviceProvider)
        : base(context, serviceProvider)
    {
    }

    protected override async Task RunAdditionalTestsAsync()
    {
        await TestAutoGeneratedIdAsync();
        await TestUniqueConstraintExceptionTypeAsync();
        await TestMergeParameterBindingAsync();
    }

    private async Task TestMergeParameterBindingAsync()
    {
        var tableName = _context.WrapObjectName("db2_merge_parameter_test");
        await using var sc = _context.CreateSqlContainer();

        sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
        try
        {
            await sc.ExecuteNonQueryAsync();
        }
        catch
        {
            // The table is absent on the first run.
        }

        try
        {
            sc.Clear();
            sc.Query.Append($"CREATE TABLE {tableName} (");
            sc.Query.Append($"{_context.WrapObjectName("id")} INTEGER NOT NULL PRIMARY KEY, ");
            sc.Query.Append($"{_context.WrapObjectName("name")} VARCHAR(100) NOT NULL, ");
            sc.Query.Append($"{_context.WrapObjectName("amount")} DECIMAL(10,2) NOT NULL)");
            await sc.ExecuteNonQueryAsync();

            var gateway = new TableGateway<Db2MergeParameterTestTable, int>(_context);
            var entity = new Db2MergeParameterTestTable { Id = 1, Name = "before", Amount = 12.34m };
            await gateway.UpsertAsync(entity);
            entity.Name = "after";
            entity.Amount = 56.78m;
            await gateway.UpsertAsync(entity);

            var loaded = await gateway.RetrieveOneAsync(1);
            if (loaded?.Name != "after" || loaded.Amount != 56.78m)
            {
                throw new Exception("Db2 MERGE parameter binding did not preserve the updated values");
            }

            CheckOk("Db2 MERGE parameter binding: typed integer, string, and decimal values: OK");
        }
        finally
        {
            sc.Clear();
            sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
            try
            {
                await sc.ExecuteNonQueryAsync();
            }
            catch
            {
                // Best-effort cleanup.
            }
        }
    }

    /// <summary>
    /// Validates that a real Db2 unique-constraint violation (SQLSTATE 23505) translates to
    /// the SPECIFIC UniqueConstraintViolationException type, not just any DatabaseException.
    /// The base TestErrorMapping() only checks for the generic DatabaseException base class —
    /// this closes the gap flagged as unverified in Phase 1 (whether Db2ExceptionTranslator's
    /// SQLSTATE-primary classification actually fires correctly against the real driver).
    /// </summary>
    private async Task TestUniqueConstraintExceptionTypeAsync()
    {
        Console.WriteLine("Running Db2 unique-constraint exception type check");

        var tableName = _context.WrapObjectName("db2_unique_test_table");

        await using var sc = _context.CreateSqlContainer();
        sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
        try
        {
            await sc.ExecuteNonQueryAsync();
        }
        catch
        {
            // Table did not exist, ignore.
        }

        try
        {
            sc.Clear();
            sc.Query.Append($@"
CREATE TABLE {tableName} (
    {_context.WrapObjectName("id")} BIGINT NOT NULL PRIMARY KEY,
    {_context.WrapObjectName("name")} VARCHAR(100) NOT NULL
)");
            await sc.ExecuteNonQueryAsync();

            var gateway = new TableGateway<Db2UniqueTestTable, long>(_context);
            var entity = new Db2UniqueTestTable { Id = 1, Name = "first" };
            var ok = await gateway.CreateAsync(entity);
            if (!ok)
            {
                throw new Exception("Db2 unique-constraint check: initial CreateAsync returned false");
            }

            var duplicate = new Db2UniqueTestTable { Id = 1, Name = "duplicate" };
            try
            {
                await gateway.CreateAsync(duplicate);
                throw new Exception(
                    "Db2 unique-constraint check: expected UniqueConstraintViolationException, none thrown");
            }
            catch (UniqueConstraintViolationException ex)
            {
                CheckOk($"Db2 unique-constraint check: correctly threw UniqueConstraintViolationException ({ex.Message[..Math.Min(80, ex.Message.Length)]}...)");
            }
        }
        finally
        {
            sc.Clear();
            sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
            try
            {
                await sc.ExecuteNonQueryAsync();
            }
            catch
            {
                // best-effort cleanup
            }
        }
    }

    [Table("db2_unique_test_table")]
    private class Db2UniqueTestTable
    {
        [Id]
        [Column("id", System.Data.DbType.Int64)]
        public long Id { get; set; }

        [Column("name", System.Data.DbType.String)]
        public string Name { get; set; } = string.Empty;
    }

    /// <summary>
    /// Validates Db2's generated-key retrieval strategy: SELECT ... FROM FINAL TABLE (INSERT ...).
    /// This is the one behavior that could not be verified against fakeDb alone in Phase 1 —
    /// it depends on the real Db2 engine actually accepting this exact wrapped-statement syntax.
    /// </summary>
    private async Task TestAutoGeneratedIdAsync()
    {
        Console.WriteLine("Running Db2 FINAL TABLE clause (auto-generated identity)");

        var tableName = _context.WrapObjectName("db2_auto_id_table");

        await using var sc = _context.CreateSqlContainer();

        sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
        try
        {
            await sc.ExecuteNonQueryAsync();
        }
        catch
        {
            // Table did not exist, ignore.
        }

        try
        {
            sc.Clear();
            sc.Query.Append($@"
CREATE TABLE {tableName} (
    {_context.WrapObjectName("id")} BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    {_context.WrapObjectName("name")} VARCHAR(100) NOT NULL
)");
            await sc.ExecuteNonQueryAsync();

            var gateway = new TableGateway<Db2AutoIdTable, long>(_context);
            var entity = new Db2AutoIdTable { Name = "final-table-test" };
            var ok = await gateway.CreateAsync(entity);

            if (!ok)
            {
                throw new Exception("Db2 FINAL TABLE: CreateAsync returned false");
            }

            if (entity.Id == 0)
            {
                throw new Exception(
                    "Db2 FINAL TABLE clause did not populate Id — SELECT ... FROM FINAL TABLE (INSERT ...) returned 0 or null");
            }

            CheckOk($"Db2 FINAL TABLE: CreateAsync populated Id = {entity.Id} via SELECT ... FROM FINAL TABLE (INSERT ...)");

            var retrieved = await gateway.RetrieveOneAsync(entity.Id);
            if (retrieved == null || retrieved.Id != entity.Id)
            {
                throw new Exception(
                    $"Db2 FINAL TABLE: RetrieveOneAsync by returned Id {entity.Id} did not find the row");
            }

            CheckOk($"Db2 FINAL TABLE: RetrieveOneAsync confirmed row exists with Id = {retrieved.Id}");
        }
        finally
        {
            sc.Clear();
            sc.Query.Append($"DROP TABLE IF EXISTS {tableName}");
            try
            {
                await sc.ExecuteNonQueryAsync();
            }
            catch
            {
                // best-effort cleanup
            }
        }
    }

    [Table("db2_auto_id_table")]
    private class Db2AutoIdTable
    {
        [Id(false)]
        [Column("id", System.Data.DbType.Int64)]
        public long Id { get; set; }

        [Column("name", System.Data.DbType.String)]
        public string Name { get; set; } = string.Empty;
    }

    [Table("db2_merge_parameter_test")]
    private class Db2MergeParameterTestTable
    {
        [Id]
        [Column("id", System.Data.DbType.Int32)]
        public int Id { get; set; }

        [Column("name", System.Data.DbType.String)]
        public string Name { get; set; } = string.Empty;

        [Column("amount", System.Data.DbType.Decimal)]
        public decimal Amount { get; set; }
    }
}
