using System.Data;
using pengdows.crud.attributes;
using pengdows.crud.enums;
using pengdows.crud.IntegrationTests.Infrastructure;
using Xunit.Abstractions;

namespace pengdows.crud.IntegrationTests.DatabaseSpecific;

/// <summary>
/// A writable [Id] upserted into a GENERATED ALWAYS AS IDENTITY column needs OVERRIDING SYSTEM
/// VALUE on PostgreSQL and YugabyteDB, for single-row and batch upsert alike (BP-117). CockroachDB
/// has no such clause; it uses GENERATED BY DEFAULT here so the same entity still upserts.
/// </summary>
[Collection("IntegrationTests")]
public sealed class PostgreSqlIdentityOverrideUpsertTests : DatabaseTestBase
{
    private static readonly SupportedDatabase[] Providers =
    {
        SupportedDatabase.PostgreSql,
        SupportedDatabase.YugabyteDb,
        SupportedDatabase.CockroachDb
    };

    public PostgreSqlIdentityOverrideUpsertTests(ITestOutputHelper output, IntegrationTestFixture fixture)
        : base(output, fixture)
    {
    }

    protected override IEnumerable<SupportedDatabase> GetSupportedProviders() =>
        base.GetSupportedProviders().Where(Providers.Contains).ToArray();

    protected override async Task SetupDatabaseAsync(SupportedDatabase provider, IDatabaseContext context)
    {
        await DropTableIfExistsAsync(context, "identity_upsert");
        var generated = provider == SupportedDatabase.CockroachDb ? "BY DEFAULT" : "ALWAYS";
        await using var sc = context.CreateSqlContainer(
            $"CREATE TABLE {IntegrationObjectNameHelper.Table(context, "identity_upsert")} (" +
            $"{context.WrapObjectName("id")} BIGINT GENERATED {generated} AS IDENTITY PRIMARY KEY, " +
            $"{context.WrapObjectName("name")} VARCHAR(40) NOT NULL)");
        await sc.ExecuteNonQueryAsync();
    }

    [SkippableFact]
    public Task Upsert_SingleAndBatch_WithExplicitIdentityValue()
    {
        return RunTestAgainstAllProvidersAsync(async (provider, context) =>
        {
            var gateway = new TableGateway<IdentityUpsertEntity, long>(context);
            var failures = new List<string>();

            try
            {
                await gateway.UpsertAsync(new IdentityUpsertEntity { Id = 100, Name = "single" }, context);
                await gateway.UpsertAsync(new IdentityUpsertEntity { Id = 100, Name = "single-updated" }, context);
            }
            catch (Exception ex)
            {
                failures.Add($"single: {ex.GetType().Name}: {ex.Message}");
            }

            try
            {
                var batch = new[]
                {
                    new IdentityUpsertEntity { Id = 200, Name = "b1" },
                    new IdentityUpsertEntity { Id = 201, Name = "b2" }
                };
                await gateway.BatchUpsertAsync(batch, context);
                batch[0].Name = "b1-updated";
                await gateway.BatchUpsertAsync(batch, context);
            }
            catch (Exception ex)
            {
                failures.Add($"batch: {ex.GetType().Name}: {ex.Message}");
            }

            Assert.True(failures.Count == 0, $"{provider}: " + string.Join(" | ", failures));

            Assert.Equal("single-updated", (await gateway.RetrieveOneAsync(100, context))!.Name);
            Assert.Equal("b1-updated", (await gateway.RetrieveOneAsync(200, context))!.Name);
            Assert.Equal("b2", (await gateway.RetrieveOneAsync(201, context))!.Name);
        });
    }
}

[Table("identity_upsert")]
public sealed class IdentityUpsertEntity
{
    [Id] [Column("id", DbType.Int64)] public long Id { get; set; }
    [Column("name", DbType.String)] public string Name { get; set; } = string.Empty;
}
